- type: static site
    name: blood-hospital-a-frontend
    publishDir: frontend/hospital_a
    buildCommand: echo "No build needed"
    envVars:
      - key: API_BASE_URL
        value: https://blood-local-hospital-a.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: static site
    name: blood-global-admin-frontend
    publishDir: frontend/global_admin
    buildCommand: echo "No build needed"
    envVars:
      - key: API_BASE_URL
        value: https://blood-global-server.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html